### ISSUE TITLE
its buggy on canary

### ISSUE THREAD

**Issue by ryudragon98** [kosshishub/CompactGuilds-BD-plugin#5]
when using canary some times the channel and server list cant be revealed in server or dm unless you hit ctrl+ , and configure the settings again by hitting save and apply then it only works for a little bit. this may be because of the update that canary had.

**Comment by TJBK** [comment]
I'm having the same issue on PTB

**Comment by TJBK** [comment]
Okay I worked out a fix for now.

```css
#hg_hoverOver {
    z-index: 9001;
}

.guilds-wrapper {
    z-index: 9002;
}
```

Not sure if it will work for everyone though I've done some messing around and it seems to be working. I can't promise it won't break custom themes that mess with z-index.
